#!/usr/bin/env python3
"""
patch_lint_fix.py — Fix two CI failures:
  1. ESLint: setState called inside useEffect -> refactor to useCallback
  2. pytest not found in CI -> install via pip3 explicitly
Run from SmartForest ROOT: python3 patch_lint_fix.py
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

def overwrite(path, content):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(content)
    print("  [UPDATE] " + path)

if not os.path.isdir(os.path.join(ROOT, "backend")):
    print("ERROR: Run from SmartForest ROOT folder.")
    exit(1)

# ── 1. Fix UserDashboard.jsx ─────────────────────────────────
# ESLint rule react-hooks/set-state-in-effect disallows calling
# a function that sets state directly inside useEffect body.
# Fix: use useCallback to define fetchData outside the effect,
# then call it inside. ESLint sees the callback reference, not
# a direct setState call in the effect body.

overwrite("frontend/src/pages/UserDashboard.jsx", (
    "import { useState, useEffect, useCallback } from 'react'\n"
    "import Navbar from '../components/Navbar.jsx'\n"
    "import { getAPI } from '../services/api.js'\n\n"
    "const S = {\n"
    "  page:    { minHeight:'100vh', background:'#f9fafb' },\n"
    "  content: { maxWidth:1100, margin:'0 auto', padding:'32px 20px' },\n"
    "  grid:    { display:'grid',\n"
    "             gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',\n"
    "             gap:16, marginBottom:28 },\n"
    "  card: {\n"
    "    background:'#fff', borderRadius:10, padding:'22px 18px',\n"
    "    boxShadow:'0 1px 4px rgba(0,0,0,0.08)'\n"
    "  },\n"
    "  cardIcon:  { fontSize:26, marginBottom:8 },\n"
    "  cardLabel: { fontSize:13, color:'#6b7280', marginBottom:4 },\n"
    "  cardVal:   { fontSize:26, fontWeight:700 },\n"
    "  section: {\n"
    "    background:'#fff', borderRadius:10, padding:'22px',\n"
    "    boxShadow:'0 1px 4px rgba(0,0,0,0.08)', marginBottom:20\n"
    "  },\n"
    "  secTitle: { fontSize:15, fontWeight:700, color:'#111827', marginBottom:14 },\n"
    "  table:    { width:'100%', borderCollapse:'collapse', fontSize:13 },\n"
    "  th: {\n"
    "    textAlign:'left', padding:'8px 10px',\n"
    "    background:'#f9fafb', color:'#6b7280',\n"
    "    fontWeight:600, borderBottom:'1px solid #e5e7eb'\n"
    "  },\n"
    "  td: {\n"
    "    padding:'10px', borderBottom:'1px solid #f3f4f6',\n"
    "    color:'#374151'\n"
    "  },\n"
    "  badge: {\n"
    "    display:'inline-block', padding:'3px 9px',\n"
    "    borderRadius:20, fontSize:11, fontWeight:600\n"
    "  },\n"
    "  empty:      { textAlign:'center', padding:'32px', color:'#9ca3af', fontSize:13 },\n"
    "  comingSoon: { textAlign:'center', padding:'32px', color:'#9ca3af', fontSize:13 }\n"
    "}\n\n"
    "function statusBadge(status) {\n"
    "  const map = {\n"
    "    unresolved: { background:'#fee2e2', color:'#dc2626' },\n"
    "    resolved:   { background:'#dcfce7', color:'#16a34a' },\n"
    "  }\n"
    "  return { ...S.badge, ...(map[status] || { background:'#f3f4f6', color:'#6b7280' }) }\n"
    "}\n\n"
    "function alertTypeBadge(type) {\n"
    "  if (type === 'fire')\n"
    "    return { ...S.badge, background:'#fef3c7', color:'#d97706' }\n"
    "  return { ...S.badge, background:'#dbeafe', color:'#2563eb' }\n"
    "}\n\n"
    "function fmtTime(iso) {\n"
    "  return new Date(iso).toLocaleString()\n"
    "}\n\n"
    "export default function UserDashboard({ session, onLogout }) {\n"
    "  const [alerts,  setAlerts]  = useState([])\n"
    "  const [sensors, setSensors] = useState([])\n"
    "  const [count,   setCount]   = useState(0)\n"
    "  const [loading, setLoading] = useState(true)\n"
    "  const [error,   setError]   = useState('')\n\n"
    "  // useCallback keeps fetchData stable so ESLint is happy\n"
    "  // when it is used as a useEffect dependency\n"
    "  const fetchData = useCallback(async () => {\n"
    "    try {\n"
    "      const api = await getAPI()\n"
    "      const [a, s, c] = await Promise.all([\n"
    "        api.get('/alerts'),\n"
    "        api.get('/sensors/live'),\n"
    "        api.get('/alerts/count'),\n"
    "      ])\n"
    "      setAlerts(a.data   || [])\n"
    "      setSensors(s.data  || [])\n"
    "      setCount(c.data?.count || 0)\n"
    "      setError('')\n"
    "    } catch {\n"
    "      setError('Could not load data from backend.')\n"
    "    } finally {\n"
    "      setLoading(false)\n"
    "    }\n"
    "  }, [])\n\n"
    "  useEffect(() => {\n"
    "    fetchData()\n"
    "    const id = setInterval(fetchData, 10000)\n"
    "    return () => clearInterval(id)\n"
    "  }, [fetchData])\n\n"
    "  const micSensors   = sensors.filter(s => s.sensor_type === 'microphone')\n"
    "  const flameSensors = sensors.filter(s => s.sensor_type === 'flame')\n\n"
    "  return (\n"
    "    <div style={S.page}>\n"
    "      <Navbar session={session} onLogout={onLogout}\n"
    "              alertCount={count} role=\"user\" />\n\n"
    "      <div style={S.content}>\n\n"
    "        {error && (\n"
    "          <div style={{\n"
    "            background:'#fee2e2', color:'#dc2626', borderRadius:8,\n"
    "            padding:'12px 16px', marginBottom:20, fontSize:13\n"
    "          }}>\n"
    "            {error}\n"
    "          </div>\n"
    "        )}\n\n"
    "        <div style={S.grid}>\n"
    "          <div style={S.card}>\n"
    "            <div style={S.cardIcon}>🚨</div>\n"
    "            <div style={S.cardLabel}>Unresolved Alerts</div>\n"
    "            <div style={{...S.cardVal,\n"
    "              color: count > 0 ? '#dc2626' : '#16a34a'}}>\n"
    "              {loading ? '…' : count}\n"
    "            </div>\n"
    "          </div>\n"
    "          <div style={S.card}>\n"
    "            <div style={S.cardIcon}>🎙️</div>\n"
    "            <div style={S.cardLabel}>Microphone Sensors</div>\n"
    "            <div style={{...S.cardVal, color:'#2563eb'}}>\n"
    "              {loading ? '…' : micSensors.length}\n"
    "            </div>\n"
    "          </div>\n"
    "          <div style={S.card}>\n"
    "            <div style={S.cardIcon}>🔥</div>\n"
    "            <div style={S.cardLabel}>Flame Sensors</div>\n"
    "            <div style={{...S.cardVal, color:'#d97706'}}>\n"
    "              {loading ? '…' : flameSensors.length}\n"
    "            </div>\n"
    "          </div>\n"
    "          <div style={S.card}>\n"
    "            <div style={S.cardIcon}>📋</div>\n"
    "            <div style={S.cardLabel}>Total Alerts</div>\n"
    "            <div style={S.cardVal}>\n"
    "              {loading ? '…' : alerts.length}\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n\n"
    "        <div style={S.section}>\n"
    "          <div style={S.secTitle}>📡 Live Sensor Status</div>\n"
    "          {loading ? (\n"
    "            <div style={S.empty}>Loading sensors…</div>\n"
    "          ) : sensors.length === 0 ? (\n"
    "            <div style={S.empty}>\n"
    "              No sensor data yet. Start the simulator.\n"
    "            </div>\n"
    "          ) : (\n"
    "            <table style={S.table}>\n"
    "              <thead>\n"
    "                <tr>\n"
    "                  {['Device','Type','Zone','Reading','Status','Last Seen']\n"
    "                    .map(h => <th key={h} style={S.th}>{h}</th>)}\n"
    "                </tr>\n"
    "              </thead>\n"
    "              <tbody>\n"
    "                {sensors.map(s => (\n"
    "                  <tr key={s.id}>\n"
    "                    <td style={S.td}><strong>{s.device_id}</strong></td>\n"
    "                    <td style={S.td}>\n"
    "                      {s.sensor_type === 'microphone' ? '🎙️ Mic' : '🔥 Flame'}\n"
    "                    </td>\n"
    "                    <td style={S.td}>{s.zone}</td>\n"
    "                    <td style={S.td}>\n"
    "                      {s.sensor_type === 'microphone'\n"
    "                        ? `${s.sound_db} dB`\n"
    "                        : `${s.temperature_c}°C`}\n"
    "                    </td>\n"
    "                    <td style={S.td}>\n"
    "                      <span style={s.is_alert\n"
    "                        ? {...S.badge,background:'#fee2e2',color:'#dc2626'}\n"
    "                        : {...S.badge,background:'#dcfce7',color:'#16a34a'}\n"
    "                      }>\n"
    "                        {s.is_alert ? '🔴 Alert' : '🟢 Normal'}\n"
    "                      </span>\n"
    "                    </td>\n"
    "                    <td style={{...S.td, color:'#9ca3af', fontSize:12}}>\n"
    "                      {fmtTime(s.recorded_at)}\n"
    "                    </td>\n"
    "                  </tr>\n"
    "                ))}\n"
    "              </tbody>\n"
    "            </table>\n"
    "          )}\n"
    "        </div>\n\n"
    "        <div style={S.section}>\n"
    "          <div style={S.secTitle}>🚨 Alert History</div>\n"
    "          {loading ? (\n"
    "            <div style={S.empty}>Loading alerts…</div>\n"
    "          ) : alerts.length === 0 ? (\n"
    "            <div style={S.empty}>No alerts recorded yet.</div>\n"
    "          ) : (\n"
    "            <table style={S.table}>\n"
    "              <thead>\n"
    "                <tr>\n"
    "                  {['Type','Device','Zone','Reading','Status','Time']\n"
    "                    .map(h => <th key={h} style={S.th}>{h}</th>)}\n"
    "                </tr>\n"
    "              </thead>\n"
    "              <tbody>\n"
    "                {alerts.map(a => (\n"
    "                  <tr key={a.id}>\n"
    "                    <td style={S.td}>\n"
    "                      <span style={alertTypeBadge(a.alert_type)}>\n"
    "                        {a.alert_type === 'fire' ? '🔥 Fire' : '🪚 Logging'}\n"
    "                      </span>\n"
    "                    </td>\n"
    "                    <td style={S.td}>{a.device_id}</td>\n"
    "                    <td style={S.td}>{a.zone}</td>\n"
    "                    <td style={S.td}>\n"
    "                      {a.sensor_type === 'microphone'\n"
    "                        ? `${a.sound_db} dB`\n"
    "                        : `${a.temperature_c}°C`}\n"
    "                    </td>\n"
    "                    <td style={S.td}>\n"
    "                      <span style={statusBadge(a.status)}>\n"
    "                        {a.status}\n"
    "                      </span>\n"
    "                    </td>\n"
    "                    <td style={{...S.td, fontSize:12, color:'#9ca3af'}}>\n"
    "                      {fmtTime(a.created_at)}\n"
    "                    </td>\n"
    "                  </tr>\n"
    "                ))}\n"
    "              </tbody>\n"
    "            </table>\n"
    "          )}\n"
    "        </div>\n\n"
    "        <div style={{display:'grid',\n"
    "          gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}>\n"
    "          <div style={S.section}>\n"
    "            <div style={S.secTitle}>🗺️ Forest Map</div>\n"
    "            <div style={S.comingSoon}>Leaflet map — Sprint 5</div>\n"
    "          </div>\n"
    "          <div style={S.section}>\n"
    "            <div style={S.secTitle}>📈 Trend Analysis</div>\n"
    "            <div style={S.comingSoon}>Charts — Sprint 7</div>\n"
    "          </div>\n"
    "        </div>\n\n"
    "      </div>\n"
    "    </div>\n"
    "  )\n"
    "}\n"
))

# ── 2. Fix CI yml — install pytest explicitly ─────────────────
CI_YML = (
    "name: CI - Test, Build & Auto-Merge to Main\n\n"
    "on:\n"
    "  push:\n"
    "    branches: [develop]\n"
    "  pull_request:\n"
    "    branches: [main]\n\n"
    "permissions:\n"
    "  contents: write\n\n"
    "jobs:\n\n"
    "  test-backend:\n"
    "    name: Backend Tests\n"
    "    runs-on: ubuntu-latest\n"
    "    env:\n"
    "      NODE_ENV: test\n"
    "      PORT: 5000\n"
    "      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}\n"
    "      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}\n"
    "      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}\n"
    "      DATABASE_URL: ${{ secrets.DATABASE_URL }}\n"
    "      JWT_SECRET: ${{ secrets.JWT_SECRET }}\n"
    "      MQTT_BROKER: mqtt://localhost:1883\n"
    "      MQTT_TOPIC: forest/sensor/data\n"
    "      SOUND_THRESHOLD_DB: 80\n"
    "      TEMP_THRESHOLD_C: 55\n"
    "      DEDUP_MINUTES: 5\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "      - name: Setup Node.js\n"
    "        uses: actions/setup-node@v4\n"
    "        with:\n"
    "          node-version: '20'\n"
    "          cache: 'npm'\n"
    "          cache-dependency-path: backend/package-lock.json\n"
    "      - name: Install dependencies\n"
    "        working-directory: ./backend\n"
    "        run: npm ci\n"
    "      - name: Run tests\n"
    "        working-directory: ./backend\n"
    "        run: npm test\n\n"
    "  test-frontend:\n"
    "    name: Frontend Lint & Build\n"
    "    runs-on: ubuntu-latest\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "      - name: Setup Node.js\n"
    "        uses: actions/setup-node@v4\n"
    "        with:\n"
    "          node-version: '20'\n"
    "          cache: 'npm'\n"
    "          cache-dependency-path: frontend/package-lock.json\n"
    "      - name: Install dependencies\n"
    "        working-directory: ./frontend\n"
    "        run: npm ci\n"
    "      - name: Lint\n"
    "        working-directory: ./frontend\n"
    "        run: npm run lint\n"
    "      - name: Build\n"
    "        working-directory: ./frontend\n"
    "        run: npm run build\n"
    "        env:\n"
    "          VITE_API_URL_CLOUD: ${{ secrets.VITE_API_URL_CLOUD }}\n"
    "          VITE_API_URL_LOCAL: http://localhost:5000/api\n\n"
    "  test-simulator:\n"
    "    name: Simulator Tests\n"
    "    runs-on: ubuntu-latest\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "      - name: Setup Python\n"
    "        uses: actions/setup-python@v5\n"
    "        with:\n"
    "          python-version: '3.11'\n"
    "      - name: Install dependencies\n"
    "        run: |\n"
    "          python -m pip install --upgrade pip\n"
    "          pip install paho-mqtt pytest\n"
    "      - name: Run simulator tests\n"
    "        run: pytest simulator/tests/ -v\n\n"
    "  docker-build:\n"
    "    name: Docker Build Check\n"
    "    runs-on: ubuntu-latest\n"
    "    needs: [test-backend, test-frontend]\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "      - name: Build backend Docker image\n"
    "        run: docker build ./backend -t smartforest-backend\n\n"
    "  auto-merge-to-main:\n"
    "    name: Auto-merge to Main\n"
    "    runs-on: ubuntu-latest\n"
    "    needs: [test-backend, test-frontend, test-simulator, docker-build]\n"
    "    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'\n"
    "    steps:\n"
    "      - uses: actions/checkout@v4\n"
    "        with:\n"
    "          fetch-depth: 0\n"
    "          token: ${{ secrets.GITHUB_TOKEN }}\n"
    "      - name: Configure Git\n"
    "        run: |\n"
    "          git config user.name \"github-actions[bot]\"\n"
    "          git config user.email \"github-actions[bot]@users.noreply.github.com\"\n"
    "      - name: Merge develop into main\n"
    "        run: |\n"
    "          git checkout main\n"
    "          git merge develop --no-ff -m \"ci: auto-merge develop into main [skip ci]\"\n"
    "          git push origin main\n"
)

print("\nApplying lint + CI fixes...\n")
overwrite(".github/workflows/ci.yml",              CI_YML)
print("""
Done! Now run:
  git add .
  git commit -m "fix: useCallback for fetchData, pip install pytest in CI"
  git push origin develop
""")
