#!/usr/bin/env python3
"""
patch_sprints_v2.py — Update SPRINTS.md: replace email with dashboard notifications
Run from SmartForest ROOT: python3 patch_sprints_v2.py
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

def overwrite(path, content):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(content)
    print("  [UPDATE] " + path)

if not os.path.isdir(os.path.join(ROOT, "backend")):
    print("ERROR: Run from SmartForest ROOT folder.")
    exit(1)

SPRINTS = (
    "# SmartForest — Agile Development Sprints\n\n"
    "**Project:** Web-Based System for Detecting Illegal Logging Activities\n"
    "**Methodology:** Agile (Scrum-inspired, solo developer)\n"
    "**Sprint Length:** 1 week per sprint\n"
    "**Branch Strategy:** develop (work) -> main (production via CI/CD)\n"
    "**Start Date:** June 2026\n\n"
    "---\n\n"
    "## Notification Strategy\n\n"
    "Alerts are delivered via the **web dashboard only** (no email).\n"
    "Rangers monitoring the dashboard see alerts in real time through:\n"
    "- Auto-refreshing AlertsTable (polls every 10 seconds)\n"
    "- Red alert badge counter on the Navbar\n"
    "- New alert rows highlighted in red with fade-in animation\n"
    "- Browser Web Notification (popup) when a new alert arrives\n"
    "- Audio beep sound on new alert (optional, can be toggled off)\n\n"
    "---\n\n"
    "## Sprint Overview\n\n"
    "| Sprint | Focus                           | Status      |\n"
    "|--------|---------------------------------|-------------|\n"
    "| 0      | Project Setup & CI/CD           | DONE        |\n"
    "| 1      | Database Models & Backend Core  | IN PROGRESS |\n"
    "| 2      | MQTT & Sensor Ingest            | PENDING     |\n"
    "| 3      | Auth & Security                 | PENDING     |\n"
    "| 4      | Frontend Dashboard              | PENDING     |\n"
    "| 5      | Map & Real-Time Alerts          | PENDING     |\n"
    "| 6      | Dashboard Notifications         | PENDING     |\n"
    "| 7      | Reporting & Alert Management    | PENDING     |\n"
    "| 8      | Testing & Hardening             | PENDING     |\n"
    "| 9      | Deployment & Documentation      | PENDING     |\n\n"
    "---\n\n"
    "## Sprint 0 — Project Setup & CI/CD\n"
    "**Duration:** Week 1 | **Status:** DONE\n\n"
    "**Goal:** Working skeleton with automated pipeline.\n\n"
    "### Completed\n"
    "- [x] Initialize Git repo with develop/main branch strategy\n"
    "- [x] Define full folder structure\n"
    "- [x] Set up Express.js backend skeleton\n"
    "- [x] Set up React/Vite frontend skeleton\n"
    "- [x] Set up Python MQTT simulator\n"
    "- [x] Write 14 passing backend tests (Jest + Supertest)\n"
    "- [x] Configure GitHub Actions CI/CD pipeline\n"
    "- [x] Auto-merge develop -> main on all tests passing\n"
    "- [x] Configure Supabase project and credentials\n"
    "- [x] Create backend/.env with all credentials\n"
    "- [x] Deploy backend to Render.com\n"
    "- [x] Deploy frontend to Vercel\n\n"
    "### Definition of Done\n"
    "- CI pipeline runs green on every push to develop\n"
    "- /api/health returns 200 on Render cloud URL\n\n"
    "---\n\n"
    "## Sprint 1 — Database Models & Backend Core\n"
    "**Duration:** Week 2 | **Status:** IN PROGRESS\n\n"
    "**Goal:** Backend reads and writes real data to Supabase.\n\n"
    "### User Stories\n"
    "- As a system, I want to save sensor readings to the database\n"
    "  so that all historical data is preserved.\n"
    "- As a ranger, I want to retrieve alerts from the API\n"
    "  so that the dashboard can display them.\n"
    "- As a developer, I want DB queries in model files\n"
    "  so that routes stay clean and testable.\n\n"
    "### Tasks\n"
    "- [ ] Implement sensorModel.js\n"
    "      saveReading(data)  -> INSERT into sensor_readings\n"
    "      getAll()           -> SELECT all readings\n"
    "      getLive()          -> SELECT latest per device_id\n"
    "- [ ] Implement alertModel.js\n"
    "      create(data)       -> INSERT into alerts\n"
    "      getAll()           -> SELECT all ORDER BY created_at DESC\n"
    "      getById(id)        -> SELECT single alert\n"
    "      resolve(id)        -> UPDATE status = resolved\n"
    "      getUnresolved()    -> SELECT where status = unresolved\n"
    "      countUnresolved()  -> COUNT for navbar badge\n"
    "- [ ] Implement userModel.js\n"
    "      getByEmail(email)  -> SELECT user by email\n"
    "      create(data)       -> INSERT new user profile\n"
    "- [ ] Wire routes to models\n"
    "      GET  /api/sensors        -> sensorModel.getAll()\n"
    "      GET  /api/sensors/live   -> sensorModel.getLive()\n"
    "      POST /api/sensors        -> sensorModel.saveReading()\n"
    "      GET  /api/alerts         -> alertModel.getAll()\n"
    "      GET  /api/alerts/count   -> alertModel.countUnresolved()\n"
    "      GET  /api/alerts/:id     -> alertModel.getById()\n"
    "      PATCH /api/alerts/:id/resolve -> alertModel.resolve()\n"
    "- [ ] Implement errorHandler.js middleware\n"
    "- [ ] Run SQL migrations on Supabase\n"
    "- [ ] Update tests to verify real DB responses\n\n"
    "### Patch File\n"
    "    python3 patch_db_models.py\n\n"
    "### Definition of Done\n"
    "- POST /api/sensors saves a row visible in Supabase dashboard\n"
    "- GET /api/alerts returns real rows (not empty array)\n"
    "- GET /api/alerts/count returns unresolved alert number\n"
    "- All 14+ tests still pass\n\n"
    "---\n\n"
    "## Sprint 2 — MQTT Ingest & Alert Detection\n"
    "**Duration:** Week 3 | **Status:** PENDING\n\n"
    "**Goal:** System automatically detects and stores alerts from sensor data.\n\n"
    "### User Stories\n"
    "- As a forest sensor, I want to publish readings via MQTT\n"
    "  so that the backend receives them in real time.\n"
    "- As the system, I want to auto-detect suspicious readings\n"
    "  so that alerts are created without manual intervention.\n\n"
    "### Tasks\n"
    "- [ ] Wire mqttService.js to call sensorModel.saveReading()\n"
    "- [ ] Implement alertService.js\n"
    "      evaluateReading(data)  -> check sound_db and vibration\n"
    "      if alert -> call alertModel.create()\n"
    "      deduplicate: skip if same device alerted in last 5 min\n"
    "- [ ] Wire mqttService -> alertService\n"
    "- [ ] Test end-to-end locally:\n"
    "      mosquitto -> simulator -> backend -> Supabase\n"
    "- [ ] Add MQTT integration test (mock broker)\n\n"
    "### Patch File\n"
    "    python3 patch_mqtt_ingest.py\n\n"
    "### Definition of Done\n"
    "- Simulator running -> readings appear in sensor_readings table\n"
    "- Sound > 80dB -> row appears in alerts table automatically\n"
    "- Duplicate alerts within 5 minutes are suppressed\n\n"
    "---\n\n"
    "## Sprint 3 — Authentication & Authorization\n"
    "**Duration:** Week 4 | **Status:** PENDING\n\n"
    "**Goal:** Only authenticated rangers can access the system.\n\n"
    "### User Stories\n"
    "- As a ranger, I want to log in with email and password\n"
    "  so that I can access the dashboard securely.\n"
    "- As the system, I want to reject unauthenticated API calls\n"
    "  so that data is not publicly accessible.\n\n"
    "### Tasks\n"
    "- [ ] Implement POST /api/auth/login (Supabase Auth)\n"
    "- [ ] Implement POST /api/auth/logout\n"
    "- [ ] Implement GET /api/auth/me\n"
    "- [ ] Implement authMiddleware.js (verify JWT Bearer token)\n"
    "- [ ] Protect all alert + sensor routes with authMiddleware\n"
    "- [ ] Update auth tests to cover protected routes\n"
    "- [ ] Implement AuthContext.jsx in frontend\n\n"
    "### Patch File\n"
    "    python3 patch_auth.py\n\n"
    "### Definition of Done\n"
    "- GET /api/alerts without token returns 401\n"
    "- POST /api/auth/login with valid creds returns JWT\n"
    "- GET /api/alerts with valid JWT returns data\n\n"
    "---\n\n"
    "## Sprint 4 — Frontend Dashboard\n"
    "**Duration:** Week 5 | **Status:** PENDING\n\n"
    "**Goal:** Rangers can log in and see live sensor data.\n\n"
    "### User Stories\n"
    "- As a ranger, I want a login screen to authenticate.\n"
    "- As a ranger, I want a dashboard showing sensor status\n"
    "  and recent alerts so I can monitor the forest.\n\n"
    "### Tasks\n"
    "- [ ] Implement Login.jsx (email + password form)\n"
    "- [ ] Implement useBackend.js (resolve cloud vs local)\n"
    "- [ ] Implement BackendStatus.jsx (no-backend error banner)\n"
    "- [ ] Implement Dashboard.jsx layout\n"
    "      summary cards: total alerts, active sensors, unresolved count\n"
    "- [ ] Implement SensorCard.jsx\n"
    "      device_id, zone, last reading, green/red status dot\n"
    "- [ ] Implement AlertsTable.jsx\n"
    "      columns: time, zone, device, sound_db, vibration, status\n"
    "      auto-refresh every 10s via useAlerts hook\n"
    "- [ ] Implement Navbar.jsx\n"
    "      logo, ranger name, unresolved alert badge, logout\n"
    "- [ ] Implement useSensors.js and useAlerts.js hooks\n\n"
    "### Patch File\n"
    "    python3 patch_frontend_dashboard.py\n\n"
    "### Definition of Done\n"
    "- Login works with Supabase ranger credentials\n"
    "- Dashboard loads sensor cards and alerts table\n"
    "- Alerts table auto-refreshes every 10 seconds\n\n"
    "---\n\n"
    "## Sprint 5 — Map & Real-Time Alert Pins\n"
    "**Duration:** Week 6 | **Status:** PENDING\n\n"
    "**Goal:** Visual map showing sensor locations with live alert pins.\n\n"
    "### User Stories\n"
    "- As a ranger, I want sensor locations on a map\n"
    "  so I know exactly where in the forest to respond.\n"
    "- As a ranger, I want alert pins to turn red\n"
    "  so I can immediately spot danger zones.\n\n"
    "### Tasks\n"
    "- [ ] Install leaflet + react-leaflet\n"
    "- [ ] Implement ForestMap.jsx\n"
    "      OpenStreetMap tiles centered on Kibiti (-7.78, 38.95)\n"
    "      green pin = normal, red pin = unresolved alert\n"
    "      popup: device_id, sound_db, vibration, timestamp\n"
    "- [ ] Implement AlertContext.jsx (global alert state)\n"
    "- [ ] Add map to Dashboard.jsx\n"
    "- [ ] Test map on mobile screen sizes\n\n"
    "### Patch File\n"
    "    python3 patch_map.py\n\n"
    "### Definition of Done\n"
    "- Map renders Kibiti region with sensor pins\n"
    "- Alert pins turn red within 10 seconds of alert firing\n"
    "- Clicking a pin shows sensor details popup\n\n"
    "---\n\n"
    "## Sprint 6 — Dashboard Notifications\n"
    "**Duration:** Week 7 | **Status:** PENDING\n\n"
    "**Goal:** Rangers are alerted instantly via the dashboard UI.\n"
    "No email — all notifications are web-based only.\n\n"
    "### User Stories\n"
    "- As a ranger watching the dashboard, I want a visible alert\n"
    "  the moment a new incident is detected so I can respond fast.\n"
    "- As a ranger, I want the page to notify me even if I am\n"
    "  on a different browser tab so I don't miss anything.\n\n"
    "### Tasks\n"
    "- [ ] Red badge counter on Navbar showing unresolved alert count\n"
    "      fetches GET /api/alerts/count every 10s\n"
    "      badge turns red and pulses when count > 0\n"
    "- [ ] New alert row highlight in AlertsTable\n"
    "      new rows flash red for 3 seconds then fade to normal\n"
    "      'NEW' badge on rows less than 1 minute old\n"
    "- [ ] Browser Web Notification (Notification API)\n"
    "      ask permission on login\n"
    "      fire popup notification when new alert detected\n"
    "      notification text: 'ALERT: [zone] - Sound [db]dB detected'\n"
    "      clicking notification focuses the browser tab\n"
    "- [ ] Audio alert beep (optional, toggle in settings)\n"
    "      short beep sound when new alert arrives\n"
    "      toggle on/off button in Navbar\n"
    "- [ ] Alert toast popup in bottom-right corner\n"
    "      appears for 5 seconds then auto-dismisses\n"
    "      shows zone, sensor, sound level\n\n"
    "### Patch File\n"
    "    python3 patch_notifications.py\n\n"
    "### Definition of Done\n"
    "- Navbar badge updates within 10 seconds of new alert\n"
    "- Browser popup notification fires when alert is created\n"
    "- Toast appears in bottom-right corner for 5 seconds\n"
    "- New alert rows highlighted red in the table\n"
    "- Audio beep fires on new alert (when toggle is ON)\n\n"
    "---\n\n"
    "## Sprint 7 — Reporting & Alert Management\n"
    "**Duration:** Week 8 | **Status:** PENDING\n\n"
    "**Goal:** Rangers can manage alerts and download reports.\n\n"
    "### User Stories\n"
    "- As a ranger, I want to mark an alert as resolved\n"
    "  so that the team knows it has been handled.\n"
    "- As an admin, I want to export all alerts as CSV\n"
    "  so I can submit evidence to authorities.\n\n"
    "### Tasks\n"
    "- [ ] Implement AlertDetail.jsx page\n"
    "      full alert info: zone, coords, sound, vibration, timestamp\n"
    "      Resolve button -> PATCH /api/alerts/:id/resolve\n"
    "      resolved alerts show green status badge\n"
    "- [ ] Implement GET /api/reports/alerts (CSV export)\n"
    "      accepts ?from=date&to=date query params\n"
    "      returns downloadable CSV file\n"
    "- [ ] Add Export CSV button to AlertsTable.jsx\n"
    "- [ ] Add filter controls to AlertsTable\n"
    "      filter by: zone, status, date range\n"
    "- [ ] Add pagination to AlertsTable (20 rows per page)\n\n"
    "### Patch File\n"
    "    python3 patch_reporting.py\n\n"
    "### Definition of Done\n"
    "- Resolve button updates alert status in Supabase\n"
    "- Resolved alerts show green in table and map\n"
    "- CSV export downloads with correct columns and data\n\n"
    "---\n\n"
    "## Sprint 8 — Testing & Hardening\n"
    "**Duration:** Week 9 | **Status:** PENDING\n\n"
    "**Goal:** System is robust, secure, and fully tested.\n\n"
    "### Tasks\n"
    "- [ ] Increase backend test coverage to 80%+\n"
    "- [ ] Add input validation (express-validator)\n"
    "- [ ] Add rate limiting on auth routes (express-rate-limit)\n"
    "- [ ] Add security headers (helmet.js)\n"
    "- [ ] Test all frontend components (React Testing Library)\n"
    "- [ ] End-to-end test: simulator -> MQTT -> DB -> dashboard\n"
    "- [ ] Load test: 10 sensors sending data simultaneously\n\n"
    "### Patch File\n"
    "    python3 patch_hardening.py\n\n"
    "### Definition of Done\n"
    "- npm test shows 80%+ coverage\n"
    "- All security headers present\n"
    "- System handles 10 concurrent sensors without errors\n\n"
    "---\n\n"
    "## Sprint 9 — Deployment & Documentation\n"
    "**Duration:** Week 10 | **Status:** PENDING\n\n"
    "**Goal:** System is live, documented, and ready for submission.\n\n"
    "### Tasks\n"
    "- [ ] Verify full cloud stack (Render + Vercel + Supabase)\n"
    "- [ ] Run final migrations on production Supabase\n"
    "- [ ] Create ranger user accounts in Supabase Auth\n"
    "- [ ] Write final README.md with setup instructions\n"
    "- [ ] Write API documentation (all endpoints + examples)\n"
    "- [ ] Draw system architecture diagram\n"
    "- [ ] Record demo video walkthrough\n"
    "- [ ] Write project report (academic submission)\n\n"
    "### Definition of Done\n"
    "- Frontend live on Vercel, backend live on Render\n"
    "- Ranger can log in, see map, receive dashboard alert\n"
    "  triggered by simulator within 10 seconds\n"
    "- All documentation committed to repo\n\n"
    "---\n\n"
    "## Patch Files Reference\n\n"
    "| Patch File                   | Sprint | Purpose                           |\n"
    "|------------------------------|--------|-----------------------------------|\n"
    "| patch.py                     | 0      | Initial project structure         |\n"
    "| patch_tests.py               | 0      | Add real Jest tests               |\n"
    "| patch_test_cleanup.py        | 0      | Fix Jest teardown warnings        |\n"
    "| patch_ci_fix.py              | 0      | Fix auto-merge CI permissions     |\n"
    "| patch_env.py                 | 0      | Create backend .env               |\n"
    "| patch_sprints_v2.py          | 0      | This sprints file                 |\n"
    "| patch_db_models.py           | 1      | DB models + wire routes to DB     |\n"
    "| patch_mqtt_ingest.py         | 2      | MQTT -> DB + alert detection      |\n"
    "| patch_auth.py                | 3      | Supabase Auth + JWT middleware    |\n"
    "| patch_frontend_dashboard.py  | 4      | React dashboard + components      |\n"
    "| patch_map.py                 | 5      | Leaflet map + alert pins          |\n"
    "| patch_notifications.py       | 6      | Dashboard alerts + browser notifs |\n"
    "| patch_reporting.py           | 7      | CSV export + alert management     |\n"
    "| patch_hardening.py           | 8      | Security + validation + coverage  |\n\n"
    "---\n\n"
    "## Daily Git Workflow\n\n"
    "```bash\n"
    "# Work on develop branch\n"
    "git add .\n"
    "git commit -m \"feat: describe what you built\"\n"
    "git push origin develop\n"
    "# GitHub Actions runs -> all tests pass -> auto-merge to main\n"
    "# Render redeploys backend, Vercel redeploys frontend\n"
    "```\n\n"
    "## Updating Sprint Progress\n\n"
    "```bash\n"
    "nano SPRINTS.md          # change [ ] to [x] as tasks complete\n"
    "git add SPRINTS.md\n"
    "git commit -m \"chore: update sprint 1 progress\"\n"
    "git push origin develop\n"
    "```\n"
)

print("\nUpdating SPRINTS.md...\n")
overwrite("SPRINTS.md", SPRINTS)
print("""
Done! Now run:
  git add SPRINTS.md
  git commit -m "docs: update sprints - dashboard notifications only, no email"
  git push origin develop
""")
